### ISSUE TITLE
Integrating external cluster managers with dask-ctl

### ISSUE THREAD

**Issue by jrbourbeau** [dask-contrib/dask-ctl#1]
Thanks for all your work here @jacobtomlinson, it's nice to see this taking shape : ) 

I was wondering what steps are needed to integrate cluster managers from external packages with `dask-ctl`. From looking through the code here, it appears the steps are something like:

1) Add a `dask_cluster_discovery` entrypoint similar to

https://github.com/dask-contrib/dask-ctl/blob/f512aa8d42b7281aa505af3eb0bb810cad656f3a/setup.py#L26-L31

to the package's `setup.py` which provides a method for generating cluster (name, class) pairs

2) The cluster manager should implement a `from_name` classmethod to create a new cluster instance from a given name

Does that sounds roughly correct, or am I missing something?

**Comment by jacobtomlinson** [comment]
Yeah that's exactly right. 

My current task is getting docs written up, both for users of the Python/CLI tools and also for developers of cluster managers. 

It's very early days here but if you have a look at the `ProxyCluster` class and discovery method you should get an idea of what is required.

**Comment by jrbourbeau** [comment]
Great! Let me know if you want a second set of eyes to review any docs : )

**Comment by jacobtomlinson** [comment]
Priorities shifted and this took a lot longer to come back to than expected, but we now have docs!

https://dask-ctl.readthedocs.io/en/latest/integrating.html

https://github.com/dask-contrib/dask-ctl/blob/main/docs/integrating.rst

@jrbourbeau if you have any time to take a look and check over the docs I'd appreciate it, but I'm going to close this issue out as resolved.
