### ISSUE TITLE
Add worker metrics option

### ISSUE THREAD

**Issue by thisismeleaving** [dask-contrib/dask-ctl#22]
Hi @jacobtomlinson I did a small amount of work to display worker metrics via this tool, but I can't push the branch.  Can you allow me to be a contributor?

![image](https://user-images.githubusercontent.com/1671355/151076238-96b1dc4d-47e0-4f3b-ab56-6af4c1bc9dbb.png)

**Comment by jacobtomlinson** [comment]
That's great. Please fork the project and push to your own branch, then raise a pull request.
